import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar from "@/components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "cloudinary-image-gallery",
  description: "Generated by Ahmad Bilal",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Navbar />
        <div className="flex">
          <div className="w-1/5">
            <SideBar />
          </div>
          <div className="w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
